palette:
  top: '#7689aa'
  bottom: '#1d84c3'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071B3'
logo: 'public://color/bartik-9d5c14f5/logo.svg'
stylesheets:
  - 'public://color/bartik-9d5c14f5/colors.css'
files:
  - 'public://color/bartik-9d5c14f5/logo.svg'
  - 'public://color/bartik-9d5c14f5/colors.css'
