favicon:
  mimetype: image/svg+xml
  path: 'public://logo.svg'
  url: 'http://bloodndn.dev.dd:8083/sites/bloodndn.dev.dd/files/logo.svg'
  use_default: 1
schema: '8000'
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
navbar_position: fixed-top
region_wells:
  navigation: ''
  navigation_secondary: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
logo:
  path: ''
  url: ''
  use_default: true
